# Arrays

## Types of Arrays

### 1. Homogeneous Arrays (Homo)
- Store **elements of the same data type**
- Example: **C Language Arrays**
- All elements must be uniform  
- Example:

```c
int arr[] = {1, 2, 3, 4};
```

---

### 2. Heterogeneous Arrays (Hetero)
- Can store **different data types**
- Common in **Python** (especially lists)

Example:

```python
arr = [10, "Hello", 3.14, True]
```

---

## Definition of an Array

An array is:

- A **collection of similar elements**  
- Stored in **contiguous memory locations**  
- Allows efficient access using **indexing**

> **Note:**  
> Traditional arrays usually contain similar data types,  
> but Python structures can also support mixed data types.

---

## Contiguous Memory Allocation

Arrays store elements in **continuous (adjacent) memory locations**.

Example:

| Index | Value | Memory Location |
|-------|-------|----------------|
| 0 | 10 | 1000 |
| 1 | 20 | 1004 |
| 2 | 30 | 1008 |

This enables:

- Faster access  
- Efficient traversal  
- Better memory management

---

## Accessing Arrays in Python

### 1. Using Python `array` Module

```python
import array as arr

a = arr.array('i', [10, 20, 30])

print(a[0])   # Access first element
```

---

### 2. Using NumPy

```python
import numpy as np

a = np.array([10, 20, 30])

print(a[1])   # Access second element
```

---

## Summary

| Feature | Homogeneous | Heterogeneous |
|---------|------------|---------------|
| Same Data Type | Yes | No |
| C Arrays | Yes | No |
| Python Lists | No | Yes |
| NumPy Arrays | Yes | No |


# Array Module

## Python Array Module (`array`)

## Importing the Array Module

Python provides the built-in `array` module for creating **homogeneous arrays** (elements must be of the same type).

```python
import array as arr
```

You can also import directly:

```python
from array import *
```

---

## Creating an Array

### Syntax

```python
array.array(typecode, elements)
```

### Example

```python
import array as arr

a = arr.array('i', [10, 20, 30, 40])

print(a)
```

Output:

```python
array('i', [10, 20, 30, 40])
```

---

# Type Codes in Python Array

| Type Code | Data Type | Size (Bytes) | Description |
|----------|-----------|--------------|-------------|
| `'b'` | int | 1 | Signed integer |
| `'B'` | int | 1 | Unsigned integer |
| `'u'` | Unicode | 2 | Unicode character |
| `'h'` | int | 2 | Signed short integer |
| `'H'` | int | 2 | Unsigned short integer |
| `'i'` | int | 2 or 4 | Signed integer |
| `'I'` | int | 2 or 4 | Unsigned integer |
| `'l'` | int | 4 | Signed long integer |
| `'L'` | int | 4 | Unsigned long integer |
| `'f'` | float | 4 | Floating point |
| `'d'` | float | 8 | Double precision float |

---

## Example Using Different Type Codes

### Integer Array

```python
a = arr.array('i', [1,2,3])
```

---

### Float Array

```python
a = arr.array('f', [1.5, 2.5, 3.5])
```

---

### Unicode Character Array

```python
a = arr.array('u', ['A', 'B', 'C'])
```

---

# Common Array Functions

## 1. append()

Adds element at end.

```python
a.append(50)
```

---

## 2. insert()

Insert at specific position.

```python
a.insert(1,100)
```

---

## 3. remove()

Removes element.

```python
a.remove(20)
```

---

## 4. pop()

Removes element by index.

```python
a.pop(2)
```

---

## 5. index()

Finds position.

```python
a.index(30)
```

---

## 6. reverse()

Reverses array.

```python
a.reverse()
```

---

## 7. extend()

Adds multiple elements.

```python
b = arr.array('i', [60,70])

a.extend(b)
```

---

## 8. buffer_info()

Shows memory address and length.

```python
a.buffer_info()
```

Example Output:

```python
(140673456789456, 5)
```

- First value → memory address  
- Second value → number of elements

---

## 9. count()

Counts occurrences.

```python
a.count(10)
```

---

## 10. tolist()

Convert array to list.

```python
a.tolist()
```

---

## 11. fromlist()

Convert list into array.

```python
a.fromlist([100,200])
```

---

# Accessing Elements

## Using Indexing

```python
print(a[0])     # First element
print(a[-1])    # Last element
```

---

# Traversing Array

```python
for i in a:
    print(i)
```

---

# Summary

## Array Creation

```python
a = arr.array('i',[10,20,30])
```

---

## Most Common Methods

| Function | Purpose |
|---------|---------|
| append() | Add element |
| insert() | Insert element |
| remove() | Delete element |
| pop() | Remove by index |
| reverse() | Reverse array |
| extend() | Merge arrays |
| count() | Count values |
| index() | Find position |
| tolist() | Convert to list |


### Array Module

In [1]:
import array as arr 

In [2]:
val = arr.array('i', [1,2,3,4,5,6])

In [3]:
print(val)

array('i', [1, 2, 3, 4, 5, 6])


In [4]:
for i in range(0,6):
    print(val[i], end =' ') #Space Separated Print end = ' '

1 2 3 4 5 6 

In [5]:
for x in val:
    print(x, end = ', ')

1, 2, 3, 4, 5, 6, 

In [6]:
#much better approch to import array
from array import * # all = *

In [7]:
val = arr.array('i', [1,2,3,4,5,6,7,8,9])

In [8]:
print(val)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
for i in range(0,len(val)):
    print(val[i], end =' ')

1 2 3 4 5 6 7 8 9 

In [10]:
for x in val:
    print(x, end = ', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 

In [11]:
# Adding Float object
val = arr.array('d', [1,2,3,4,5,6,7,8,9.6])

In [ ]:
for i in range(0,len(val)):
    print(val[i], end =' ')

1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.6 

In [14]:
# To store Characters
val = arr.array('u', ['a','b','c','d'])

In [15]:
for i in range(0,len(val)):
    print(val[i], end =' ')

a b c d 

In [16]:
val = arr.array('i', [1,2,3,4,5,6,7,8,9])

In [17]:
for i in range(0,len(val)):
    print(val[i], end =' ')

1 2 3 4 5 6 7 8 9 

In [18]:
print(val.typecode)

i


In [22]:
val.reverse()
for i in range(0,len(val)):
    print(val[i], end=' ')

9 8 7 6 5 4 3 2 1 

In [ ]:
val.insert(1,50)
for i in range(0,len(val)):
    print(val[i], end=' ') 
# here no element is deleted, Only shifting occured

9 50 50 8 7 6 5 4 3 2 1 

In [27]:
val.append(100)
# here we add 100 at the last of the list
# lets say we want to add 200 at 3rd position
val[2] = 200
for i in range(0,len(val)):
    print(val[i], end=' ') 
# also whenever you use append it add every time you ran the code so if i ran code 3 times 100 will be added 3 times at the back of the list

9 50 200 8 7 6 5 4 3 2 1 100 100 100 

In [34]:
copyArray = array(val.typecode,(x*2 for x in val)) # we are copying val and import all the elements of val
for i in range(0,len(val)):
    print(copyArray[i], end=' ') 

18 100 400 16 14 12 10 8 6 4 2 200 200 200 

In [38]:
copyArray.pop(3) # it will delete the element of index 3
for i in range(0,len(copyArray)):
    print(copyArray[i], end=' ') 
# if we use 
# copyArray.pop() # it will work as stack Last in first out 
# Without giving index it removes last digit

18 100 400 8 6 4 2 200 200 200 

In [44]:
copyArray.remove(400)
for i in range(0,len(copyArray)):
    print(copyArray[i], end=' ') 
# this directly remove 400 from the list

18 100 16 14 12 10 8 6 4 2 200 200 200 

In [ ]:
# Slicing
# a = val[start index : end index]
val = array('i', [1,2,3,4,5,6,7,8,9])
abc = val[2:5] # [start:stop:step]
for i in range(0,len(abc)):
    print(abc[i], end=' ') 

3 4 5 

In [49]:
abc = val[2:-3]
for i in range(0,len(abc)):
    print(abc[i], end=' ') 

3 4 5 6 

In [51]:
abc = val[::-1] # this reverse the list
for i in range(0,len(abc)):
    print(abc[i], end=' ') 

9 8 7 6 5 4 3 2 1 

In [52]:
# When we want input from user
arr = array('i', [])

n = int(input('Enter a number: '))
for i in range(0,n):
    arr.append(int(input('Enter next input here: ')))

for x in arr:
    print(x, end =' ') 

10 15 20 25 50 

In [55]:
# How to check index id
arr = array('i', [12,23,45,234,134,235])
i = arr.index(134)
print(i)


4


### Numpy Module

In [61]:
import numpy as np

In [63]:
from numpy import * # with this we dont need to write np also we can directly make array

In [65]:
val = array([1,2,3,4]) # Here we dont need to add typecode
for x in val:
    print(x, end = " ")

1 2 3 4 

In [67]:
# Benefit of using numpy first we don't need to add typecode
# Here we can make heterogenous array only in numpy module in python

val = val = array([1,2,3,4.5,'a'])
for x in val:
    print(x, end = " ")

1 2 3 4.5 a 

In [68]:
# You can also mention data type here

val = val = array([1,2,3,4], float)
for x in val:
    print(x, end = " ")

1.0 2.0 3.0 4.0 

In [ ]:
# linespace 3 parameters

val = linspace(10, 20, 5)
for x in val:
    print(x, end = " ")

10.0 12.5 15.0 17.5 20.0 

In [75]:
# arange 3 parameters

val = arange(10, 20, 2) # 5 = comman difference
for x in val:
    print(x, end = " ")

10 12 14 16 18 

In [76]:
# logspace
val = logspace(10, 20, 2) 
for x in val:
    print(x, end = " ")

10000000000.0 1e+20 

In [79]:
# Zeros 

val = zeros(10)
for x in val:
    print(x, end = " ")


0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 

In [80]:
# Ones

val = ones(10)
for x in val:
    print(x, end = " ")

1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 

In [81]:
# Full

val = full(10,5)
for x in val:
    print(x, end = " ")

5 5 5 5 5 5 5 5 5 5 

In [82]:
# Multi-dimensional arrays

In [83]:
# Zero Dim

zero = array(10)
print(zero)

10


In [84]:
# 1-D 

one = array([1,2,3,4,5])
print(one)

[1 2 3 4 5]


In [85]:
# 2-D

two = array([[1,2,3],[4,5,6],[7,8,9]])
print(two)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
# 3-D

three = array([[[1,2,3],[4,5,6],[7,8,9]]])
print(three)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
three_2 = array([[[1,2], [3,4]],[[5,6],[7,8]]])
print(three_2) # But it needs to be homogeneous

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## inf logic
### Why do we use it here?

We need `second_max` to start at some value. The options are:

```python
second_max = None          # ❌ Python can't compare None with numbers
second_max = 0             # ❌ Breaks if all numbers are negative
second_max = arr[1]        # ❌ Might accidentally skip the real answer
second_max = float('-inf') # ✅ Always safe — any real number beats it
```

It's basically saying:

> "I haven't found a second largest yet, but I'm ready to accept anything."

---

## A real-life analogy

Imagine a high score leaderboard.

Before anyone plays, the **#2 slot says `−∞`**.

The first person who scores anything — even 1 point — immediately becomes #2.

That’s exactly what `float('-inf')` does here.

---

## The twin you'll also see

```python
float('inf')   # positive infinity — every number is smaller than it
```

You'll use this when finding minimum values:

```python
min_val = float('inf')   # same idea, opposite direction
```

---

## Bookmark this in your brain 🧠

- Finding **max** → initialize with `float('-inf')`
- Finding **min** → initialize with `float('inf')`

You'll use these two lines hundreds of times in your coding life. Now you know why.

# 🚀 Move Zeroes

## 🧬 The Biology Analogy First

Imagine you're looking at a cell sample under a microscope:

- **Healthy cells** → non-zero numbers  
- **Dead cells** → zeroes  

🎯 **Goal:** Push all dead cells to the right, keep healthy cells on the left — **in their original order**

**Example:**
Before: [0, 1, 0, 3, 12]
After: [1, 3, 12, 0, 0]

✅ The healthy cells **(1, 3, 12)** kept their order — we just removed the dead ones from between them.

---

## 🧠 The Two Pointer Idea — Plain English

Use **two pointers**, both starting from the left:

- **slow pointer** → marks *where the next healthy cell should go*
- **fast pointer** → scouts ahead looking for healthy cells
[0, 1, 0, 3, 12]
↑
slow
↑
fast


---

## ⚙️ How It Works

- `fast` sees **0** → dead cell → skip  
- `fast` sees **1** → healthy → swap with `slow`, move `slow`  
- `fast` sees **0** → skip  
- `fast` sees **3** → swap, move `slow`  
- `fast` sees **12** → swap, move `slow`  

🎯 **Final Result:**

[1, 3, 12, 0, 0] ✅

---

## 🔍 Step-by-Step Visualization
arr = [0, 1, 0, 3, 12]

slow = 0, fast = 0

fast=0 → arr[0]=0 → dead → skip → fast=1

fast=1 → arr[1]=1 → healthy → swap(arr[slow], arr[fast])
[1, 0, 0, 3, 12]
slow=1, fast=2

fast=2 → arr[2]=0 → dead → skip → fast=3

fast=3 → arr[3]=3 → healthy → swap(arr[slow], arr[fast])
[1, 3, 0, 0, 12]
slow=2, fast=4

fast=4 → arr[4]=12 → healthy → swap(arr[slow], arr[fast])
[1, 3, 12, 0, 0]
slow=3, fast=5

fast=5 → out of bounds → STOP ✅

---

## 📜 The Rule (Core Logic)
if fast pointer sees a NON-ZERO:
swap it with slow pointer position
move slow forward

always move fast forward

---

## ⚡ Key Insight

- Maintains **relative order** (stable)
- Done **in-place** (no extra space)
- Time complexity: **O(n)**

---

## 🧠 Mental Model

> "Slow builds the final answer. Fast finds the next useful element."

# 🚀 Remove Duplicates (Sorted Array)

## 🧠 Plain English First

Given a **sorted array**, remove duplicates so each element appears only once.

**Example:**
Input: [1, 1, 2, 3, 3, 4]
Output: [1, 2, 3, 4]

---

## 📌 Why "Sorted" Matters

Because duplicates are always **next to each other**:


[1, 1, 2, 3, 3, 4]
↑ duplicate sits beside original


❗ If it was unsorted:

[1, 3, 1, 2, 3]

Duplicates are scattered → much harder.

👉 Sorting gives you **structure = easy detection**

---

## 🔁 The Pattern — Same as Move Zeroes

Two pointers again:

- **slow pointer** → where next *unique* element should go  
- **fast pointer** → scans array  

💡 Only change is the definition of "valid":

- Move Zeroes → valid = **non-zero**
- Remove Duplicates → valid = **different from previous**

---

## 🔍 Step-by-Step Trace


arr = [1, 1, 2, 3, 3, 4]

slow = 0

fast=0 → arr[0]=1 → first element → always keep

fast=1 → arr[1]=1 → same as arr[slow]=1 → duplicate → skip

fast=2 → arr[2]=2 → different from arr[slow]=1 → keep
slow=1 → arr[1]=2

fast=3 → arr[3]=3 → different from arr[slow]=2 → keep
slow=2 → arr[2]=3

fast=4 → arr[4]=3 → same as arr[slow]=3 → duplicate → skip

fast=5 → arr[5]=4 → different from arr[slow]=3 → keep
slow=3 → arr[3]=4


---

## ✅ Final State


[1, 2, 3, 4, ?, ?]


✔ First `slow + 1 = 4` elements are unique  
✔ Ignore the rest

---

## 📜 The Rule (Core Logic)


if arr[fast] != arr[slow]:
move slow forward
place arr[fast] at arr[slow]

always move fast forward


---

## ⚡ Key Insights

- Works because array is **sorted**
- Done **in-place** (no extra space)
- Time complexity: **O(n)**

---

## 🧠 Mental Model

> "Slow builds the unique list. Fast finds the next new value."

---

## 🔥 Pattern Connection

Both problems follow the same skeleton:

| Problem              | Condition (valid element)       |
|---------------------|--------------------------------|
| Move Zeroes         | `arr[fast] != 0`               |
| Remove Duplicates   | `arr[fast] != arr[slow]`       |

👉 Same engine, different rule.